Update Bandit Scan.yml

diff --git a/.github/workflows/Bandit Scan.yml b/.github/workflows/Bandit Scan.yml
--- a/.github/workflows/Bandit Scan.yml
+++ b/.github/workflows/Bandit Scan.yml
@@ -34,13 +34,5 @@ jobs:
           echo "Running Bandit on Python files:"
           find . -type f -name "*.py" | while read -r file; do
             echo "Scanning file: $file"
-            echo "Scanning file: $file" >> bandit_results.txt  # Append file name to results
-            bandit "$file" >> bandit_results.txt  # Append results to file
+            bandit "$file" || true  # Continue execution even if Bandit returns non-zero exit code
           done
-
-      - name: Upload Bandit results as artifact
-        if: github.actor == 'nesrinetestcs'
-        uses: actions/upload-artifact@v2
-        with:
-          name: bandit-results
-          path: bandit_results.txt
